"""multi-language support

Revision ID: 638009898d50
Revises: d501f0984ad6
Create Date: 2024-06-14 23:16:02.174449

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "638009898d50"
down_revision = "d501f0984ad6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_article", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("translation_of_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_blog_article_language_id"), ["language_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_blog_article_translation_of_id"),
            ["translation_of_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_blog_article_translation_of_id",
            "blog_article",
            ["translation_of_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_language_language_id", "language", ["language_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_article", schema=None) as batch_op:
        batch_op.drop_constraint("fk_language_language_id", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_blog_article_translation_of_id", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_blog_article_translation_of_id"))
        batch_op.drop_index(batch_op.f("ix_blog_article_language_id"))
        batch_op.drop_column("translation_of_id")
        batch_op.drop_column("language_id")

    # ### end Alembic commands ###
