"""blog integration

Revision ID: d501f0984ad6
Revises: cdeb2f3d4bbf
Create Date: 2024-06-14 10:48:13.229245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd501f0984ad6'
down_revision = 'cdeb2f3d4bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_author_name'), ['name'], unique=False)

    op.create_table('blog_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_user_customer_id'), ['customer_id'], unique=False)

    op.create_table('blog_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_author.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_article_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_article_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_article_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_article_title'), ['title'], unique=False)

    op.create_table('blog_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_session_user_id'), ['user_id'], unique=False)

    op.create_table('blog_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_article.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['blog_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_view_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_view_timestamp'))

    op.drop_table('blog_view')
    with op.batch_alter_table('blog_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_session_user_id'))

    op.drop_table('blog_session')
    with op.batch_alter_table('blog_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_article_title'))
        batch_op.drop_index(batch_op.f('ix_blog_article_timestamp'))
        batch_op.drop_index(batch_op.f('ix_blog_article_product_id'))
        batch_op.drop_index(batch_op.f('ix_blog_article_author_id'))

    op.drop_table('blog_article')
    with op.batch_alter_table('blog_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_user_customer_id'))

    op.drop_table('blog_user')
    with op.batch_alter_table('blog_author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_author_name'))

    op.drop_table('blog_author')
    # ### end Alembic commands ###
